site_name: Quelonio — Biblia Cervecera

theme:
  name: material
  language: es

docs_dir: docs

nav:
  - Inicio: index.md
  - Mapa general: 99_Indice_y_Mapas/Mapa_General_Quelonio.md
  - Índice total: 99_Indice_y_Mapas/Indice_Total.md
  - Agua: 01_Agua/01_Agua.md
  - Malta: 02_Malta/02_Malta.md
  - Levadura: 03_Levadura/03_Levadura.md
  - Lúpulo: 04_Lupulo/04_Lupulo.md
  - IPA Moderna: 05_Sistemas_IPA_Moderna/05_Sistemas_IPA_Moderna.md
  - Procesos QA/QC: 06_Procesos_QA_QC/06_Procesos_QA_QC.md

plugins:
  - search
  - roamlinks

validation:
  unrecognized_links: warn
  absolute_links: warn  
